function [mag,mag_inf,susc,susc_inf,emed,emed_inf,Cv,Cv_inf]=expTeoricasIsing1d(T,H,N)
bv=1./T;
i=0;
for b=bv
    i=i+1;
mag(i)=(exp(2*b)*sinh(b*H)*((exp(2*b)*cosh(b*H)+ ...
sqrt(exp(4*b)*sinh(b*H)^2+1))^N-(exp(2*b)*cosh(b*H)-sqrt(exp(4*b)*sinh(b*H)^2+1))^N)*N)...
/(sqrt(exp(4*b)*sinh(b*H)^2+1)*((exp(2*b)*cosh(b*H)+sqrt(exp(4*b)*sinh(b*H)^2+1))^N+...
(exp(2*b)*cosh(b*H)-sqrt(exp(4*b)*sinh(b*H)^2+1))^N));

susc(i)=(b*exp(2*b)*N*(-cosh(b*H)*(exp(2*b)*cosh(b*H)-sqrt(exp(4*b)*sinh(b*H)^2+1))^(2*N)+cosh(b*H)*(exp(2*b)*cosh(b*H)+sqrt(exp(4*b)*sinh(b*H)^2+1))^(2*N)+4*exp(2*b)*sinh(b*H)^2*...
sqrt(exp(4*b)*sinh(b*H)^2+1)*(exp(2*b)*cosh(b*H)-sqrt(exp(4*b)*sinh(b*H)^2+1))^N*(exp(2*b)*cosh(b*H)+sqrt(exp(4*b)*sinh(b*H)^2+1))^N*N))/((1+exp(4*b)*sinh(b*H)^2)^(3/2)*...
((exp(2*b)*cosh(b*H)-sqrt(exp(4*b)*sinh(b*H)^2+1))^N+(exp(2*b)*cosh(b*H)+sqrt(exp(4*b)*sinh(b*H)^2+1))^N)^2);

emed(i)=-((-(-2*exp(-2*b)+2*exp(2*b)*H*cosh(b*H)*sinh(b*H)+2*exp(2*b)*sinh(b*H)^2)/(2*sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))+exp(b)*H*sinh(b*H)+exp(b)*cosh(b*H))*(exp(b)*cosh(b*H)-sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^(N-1)*N+...
((-2*exp(-2*b)+2*exp(2*b)*H*cosh(b*H)*sinh(b*H)+2*exp(2*b)*sinh(b*H)^2)/(2*sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))+exp(b)*H*sinh(b*H)+exp(b)*cosh(b*H))*(exp(b)*cosh(b*H)+sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^(N-1)*N)/(...
(exp(b)*cosh(b*H)+sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^N+(exp(b)*cosh(b*H)-sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^N);


emed_inf(i)=-((-1+exp(4*b)*H*cosh(b*H)*sinh(b*H)+...
    exp(4*b)*sinh(b*H)^2+exp(2*b)*cosh(b*H)*sqrt(exp(4*b)*sinh(b*H)^2+1)...
    +exp(2*b)*H*sinh(b*H)*sqrt(exp(4*b)*sinh(b*H)^2+1))*N)...
    /(sqrt(exp(4*b)*sinh(b*H)^2+1)*(sqrt(exp(4*b)*sinh(b*H)^2+1)+exp(2*b)*cosh(b*H)));

Cv_inf(i)=(b^2*exp(2*b)*(4*cosh(b*H)+H^2*cosh(b*H)+exp(4*b)*H^2*cosh(b*H)^3+4*H*sinh(b*H)+4*exp(4*b)*H*cosh(b*H)^2*sinh(b*H)+8*exp(4*b)*cosh(b*H)*sinh(b*H)^2+exp(4*b)*H^2*...
cosh(b*H)*sinh(b*H)^2+4*exp(4*b)*H*sinh(b*H)^3+2*exp(2*b)*H^2*cosh(b*H)^2*sqrt(exp(4*b)*sinh(b*H)^2+1)+8*exp(2*b)*H*cosh(b*H)*sinh(b*H)*sqrt(exp(4*b)*sinh(b*H)^2+1)+8*exp(2*b)*...
sinh(b*H)^2*sqrt(exp(4*b)*sinh(b*H)^2+1))*N)/((1+exp(4*b)*sinh(b*H)^2)^(3/2)*(exp(2*b)*cosh(b*H)+sqrt(exp(4*b)*sinh(b*H)^2+1))^2);

Cv(i)=-b^2*((((-(-2*exp(-2*b)+2*exp(2*b)*H*cosh(b*H)*sinh(b*H)+2*exp(2*b)*sinh(b*H)^2)/(2*sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))+exp(b)*H*sinh(b*H)+exp(b)*cosh(b*H))*(exp(b)*cosh(b*H)-sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^(N-1)...
*N+((-2*exp(-2*b)+2*exp(2*b)*H*cosh(b*H)*sinh(b*H)+2*exp(2*b)*sinh(b*H)^2)/(2*sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))+exp(b)*H*sinh(b*H)+exp(b)*cosh(b*H))*(exp(b)*cosh(b*H)+sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^(N-1)*N)^(2))/(...
((exp(b)*cosh(b*H)-sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^N+(exp(b)*cosh(b*H)+sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^N)^2)-((exp(b)*cosh(b*H)+sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^(N-1)*(-...
(-2*exp(-2*b)+2*exp(2*b)*H*cosh(b*H)*sinh(b*H)+2*exp(2*b)*sinh(b*H)^2)^2/(4*(exp(-2*b)+exp(2*b)*sinh(b*H)^2)^(3/2))+(4*exp(-2*b)+2*exp(2*b)*H^2*cosh(b*H)^2+8*exp(2*b)*H*cosh(b*H)*sinh(b*H)+4*exp(2*b)*sinh(b*H)^2+2*exp(2*b)*H^2*sinh(b*H)^2)/(2*sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))...
+2*exp(b)*H*sinh(b*H)+exp(b)*H^2*cosh(b*H)+exp(b)*cosh(b*H))*N+(exp(b)*cosh(b*H)-sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^(N-1)*(...
(-2*exp(-2*b)+2*exp(2*b)*H*cosh(b*H)*sinh(b*H)+2*exp(2*b)*sinh(b*H)^2)^2/(4*(exp(-2*b)+exp(2*b)*sinh(b*H)^2)^(3/2))-(4*exp(-2*b)+2*exp(2*b)*H^2*cosh(b*H)^2+8*exp(2*b)*H*cosh(b*H)*sinh(b*H)+4*exp(2*b)*sinh(b*H)^2+2*exp(2*b)*H^2*sinh(b*H)^2)/(2*sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))...
+2*exp(b)*H*sinh(b*H)+exp(b)*H^2*cosh(b*H)+exp(b)*cosh(b*H))*N+(exp(b)*cosh(b*H)+exp(b)*H*sinh(b*H)-(-2*exp(-2*b)+2*exp(2*b)*H*cosh(b*H)*sinh(b*H)+2*exp(2*b)*sinh(b*H)^2)/(2*sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b))))^2*...
(exp(b)*cosh(b*H)-sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^(N-2)*(N-1)*N+(exp(b)*cosh(b*H)+exp(b)*H*sinh(b*H)+(-2*exp(-2*b)+2*exp(2*b)*H*cosh(b*H)*sinh(b*H)+2*exp(2*b)*sinh(b*H)^2)/(2*sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b))))^2*...
(exp(b)*cosh(b*H)+sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^(N-2)*(N-1)*N)/((exp(b)*cosh(b*H)+sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^N+(exp(b)*cosh(b*H)-sqrt(exp(2*b)*sinh(b*H)^2+exp(-2*b)))^N));


end

mag=mag/N;
emed=emed/N;
emed_inf=emed_inf/N;
Cv=Cv/N;
Cv_inf=Cv_inf/N;
mag_inf=sinh(H./T)./sqrt((sinh(H./T)).^2+exp(-4./T));
susc_inf=(bv.*exp(2*bv).*cosh(bv*H))./(1+exp(4*bv).*sinh(bv*H).^2).^(3/2);
susc=susc/N;
end